[tool.ruff]
line-length = 100
extend-ignore = ["E203", "W503"]
select = ["E", "F", "W", "C90", "B", "TC" ]

[tool.ruff.targets]
exclude = [".venv", "venv", "build", "dist", "__pycache__", "node_modules"]
